language: python
notifications:
  email:
    recipients:
      - chenjiandongx@qq.com
    on_success: change # default: change
    on_failure: always # default: always
python:
  - 3.6
before_install:
  - pip install -r requirements.txt
script:
  - python3 subscribe_one.py
